// File generated by FlutterFire CLI.
// After creating your Firebase project, run:
//   flutterfire configure
// This will replace this placeholder with your real Firebase options.
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'run flutterfire configure.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // PLACEHOLDER — replace via `flutterfire configure`

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6kzV-xgyIbIpVaIWdXVFztm_dUk_SNpQ',
    appId: '1:20117320928:web:21c46c853afb39cc324c85',
    messagingSenderId: '20117320928',
    projectId: 'keychain-shop',
    authDomain: 'keychain-shop.firebaseapp.com',
    storageBucket: 'keychain-shop.firebasestorage.app',
    measurementId: 'G-D0F1E24E34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAffWWWd9Jo6DS5MTTNFF_h6LXef3v8gQU',
    appId: '1:20117320928:android:a469e98a7423c8f9324c85',
    messagingSenderId: '20117320928',
    projectId: 'keychain-shop',
    storageBucket: 'keychain-shop.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWqpJB2NN_cpuMwGT1wJwpzk1P3x-aQtQ',
    appId: '1:20117320928:ios:007fd7dc04bbe1d1324c85',
    messagingSenderId: '20117320928',
    projectId: 'keychain-shop',
    storageBucket: 'keychain-shop.firebasestorage.app',
    iosBundleId: 'com.keychainshop.keychainShop',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWqpJB2NN_cpuMwGT1wJwpzk1P3x-aQtQ',
    appId: '1:20117320928:ios:59d49cec0e04e547324c85',
    messagingSenderId: '20117320928',
    projectId: 'keychain-shop',
    storageBucket: 'keychain-shop.firebasestorage.app',
    iosBundleId: 'com.example.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6kzV-xgyIbIpVaIWdXVFztm_dUk_SNpQ',
    appId: '1:20117320928:web:4c9ee3287d813e6e324c85',
    messagingSenderId: '20117320928',
    projectId: 'keychain-shop',
    authDomain: 'keychain-shop.firebaseapp.com',
    storageBucket: 'keychain-shop.firebasestorage.app',
    measurementId: 'G-BKX9RRLJ5N',
  );
}
